### ISSUE TITLE
Switch on D8 pin

### ISSUE THREAD

**Issue by ncanbr** [ialex87/smart-vacuum-garage#1]
Hi ialex87. I love the project, and will definately make two garages for some built in selfing unit.

I see you have a switch on the D8 pin, but I don't see in the parts list? Can you elaborate a bit on that?

**Comment by ialex87** [comment]
Hey, thanks for the comment. That's actually used for the push button, sort of manual override :) I had in plans to build it, but never did, however the code is there. Feel free to ignore that if you don't need a push button.
Cheers!

**Comment by ncanbr** [comment]
It makes sense to have an overwrite, but i guess it still would be dependant on HASS. Thanks for the response.
